### ISSUE TITLE
Implementation of TimSort Algorithm

### ISSUE THREAD

**Issue by aakritiguptaa** [MU-Enigma/Hacktoberfest22#325]
Hello Maintainers!

I would like to work on implementing TimSort Algorithm, an advanced sorting Algorithm.
This issue is beyond the DSA question previously mentioned.

If that doesn't violate the contributing rules of the repository, I would like to be assigned the issue
Thank you!

Regards
Aakriti

**Comment by 0xd1r** [comment]
### Comments

Add it in as a separate folder if you wish to solve it.
Sorry about such a late reply.
