### ISSUE TITLE
Error in README.md for Type_3 Level_1 Problem2: Happy Number

### ISSUE THREAD

**Issue by SuchirRP** [MU-Enigma/Hacktoberfest22#57]
*Type_3 Level_1 Problem2: Happy Number*
**Issue:** The examples for the problem were 12 + 92 = 82, 82 + 22 = 68, 62 + 82 = 100, 12 + 02 + 02 = 1 with constraint 1 <= n <= 231 - 1 when they should have been 1^2 + 9^2 = 82, 8^2 + 2^2 = 68, 6^2 + 8^2 = 100, 1^2 + 0^2 + 0^2 = 1 with constraint 1 <= n <= 2^31 - 1

**Comment by SuchirRP** [comment]
Fixed README.md and opened PR #56

**Comment by xLAVAxMASTERx** [comment]
fixed closing issue , Thank you
